# Generated by Django 5.2.4 on 2025-07-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroP', '0003_remove_produto_ativo_remove_produto_categoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
